/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BankAccount {
  'status' : AccountStatus,
  'ifscCode' : string,
  'accountHolderName' : string,
  'bankName' : string,
  'employeeId' : string,
  'accountType' : string,
  'submissionDate' : Time,
  'accountNumber' : string,
}
export interface BankAccountInput {
  'ifscCode' : string,
  'accountHolderName' : string,
  'bankName' : string,
  'accountType' : string,
  'accountNumber' : string,
}
export interface ChatMessage {
  'message' : string,
  'timestamp' : Time,
  'recipientId' : string,
  'senderId' : string,
}
export interface ChatMessageInput {
  'recipient' : string,
  'sender' : string,
  'message' : string,
}
export interface Employee {
  'id' : string,
  'username' : string,
  'fullName' : string,
  'registrationDate' : Time,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBankAccount' : ActorMethod<[string, BankAccountInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEmployee' : ActorMethod<[string, string, string], undefined>,
  'deleteBankAccount' : ActorMethod<[string], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getBankAccounts' : ActorMethod<[], Array<BankAccount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[string, string], Array<ChatMessage>>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMessagesByRecipient' : ActorMethod<[string], Array<ChatMessage>>,
  'getMyBankAccounts' : ActorMethod<[], Array<BankAccount>>,
  'getPendingBankAccounts' : ActorMethod<[], Array<BankAccount>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEmployee' : ActorMethod<[Employee], undefined>,
  'sendMessage' : ActorMethod<[ChatMessageInput], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateBankAccountStatus' : ActorMethod<[string, AccountStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];