/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BankAccountInput = IDL.Record({
  'ifscCode' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'accountType' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const AccountStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BankAccount = IDL.Record({
  'status' : AccountStatus,
  'ifscCode' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'employeeId' : IDL.Text,
  'accountType' : IDL.Text,
  'submissionDate' : Time,
  'accountNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
  'recipientId' : IDL.Text,
  'senderId' : IDL.Text,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'fullName' : IDL.Text,
  'registrationDate' : Time,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const ChatMessageInput = IDL.Record({
  'recipient' : IDL.Text,
  'sender' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBankAccount' : IDL.Func([IDL.Text, BankAccountInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteBankAccount' : IDL.Func([IDL.Text], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMessagesByRecipient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getMyBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
  'getPendingBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEmployee' : IDL.Func([Employee], [], []),
  'sendMessage' : IDL.Func([ChatMessageInput], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateBankAccountStatus' : IDL.Func([IDL.Text, AccountStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BankAccountInput = IDL.Record({
    'ifscCode' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'accountType' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const AccountStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BankAccount = IDL.Record({
    'status' : AccountStatus,
    'ifscCode' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'employeeId' : IDL.Text,
    'accountType' : IDL.Text,
    'submissionDate' : Time,
    'accountNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const ChatMessage = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Time,
    'recipientId' : IDL.Text,
    'senderId' : IDL.Text,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'fullName' : IDL.Text,
    'registrationDate' : Time,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const ChatMessageInput = IDL.Record({
    'recipient' : IDL.Text,
    'sender' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBankAccount' : IDL.Func([IDL.Text, BankAccountInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteBankAccount' : IDL.Func([IDL.Text], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMessagesByRecipient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getMyBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
    'getPendingBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEmployee' : IDL.Func([Employee], [], []),
    'sendMessage' : IDL.Func([ChatMessageInput], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateBankAccountStatus' : IDL.Func([IDL.Text, AccountStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };